# Generated by Django 4.1 on 2022-08-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_delete_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='Tiger', max_length=100),
        ),
    ]
